development:
  adapter: postgis
  encoding: unicode
  database: todo_api_dev
  pool: 5

test:
  adapter: postgis
  encoding: unicode
  database: todo_api_test
  pool: 5

production:
  url: 'test'
  adapter: postgis
  encoding: unicode
  database: todo_api_prod
  pool: 5
